CREATE TABLE TBL_TEST(
	ID VARCHAR2(1000) PRIMARY KEY,
	NAME VARCHAR2(500)
);

INSERT INTO TBL_TEST
VALUES ('jungmin0917', '황정민');
INSERT INTO TBL_TEST
VALUES ('test0123', '홍길동');

SELECT * FROM TBL_TEST;