CREATE SEQUENCE SEQ_BOARD;

-- 시퀀스 시작값 초기화
-- 이건 오라클 18 버전부터 됨
ALTER SEQUENCE SEQ_BOARD RESTART WITH 1;

-- 그냥 시퀀스 삭제 후 다시 만들자..
DROP SEQUENCE SEQ_BOARD;

CREATE TABLE JUNGMIN_BOARD(
	BNO NUMBER(10) PRIMARY KEY,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

INSERT INTO JUNGMIN_BOARD
(BNO, TITLE, CONTENT, WRITER, REGDATE, UPDATEDATE)
VALUES(SEQ_BOARD.NEXTVAL, '테스트 제목2', '테스트 내용2', 'user01', SYSDATE, SYSDATE);

SELECT * FROM JUNGMIN_BOARD ORDER BY BNO DESC;

TRUNCATE TABLE JUNGMIN_BOARD;