CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE JUNGMIN_BOARD(
	BNO NUMBER(10) PRIMARY KEY,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	REGDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE
);

SELECT * FROM JUNGMIN_BOARD;