
CREATE TABLE JUNGMIN_FILE(
	UUID VARCHAR2(1000) CONSTRAINT PK_FILE PRIMARY KEY,
	UPLOAD_PATH VARCHAR2(1000),
	FILE_NAME VARCHAR2(1000),
	FILE_TYPE CHAR(1),
	BNO NUMBER(10),
	CONSTRAINT FK_FILE 
	FOREIGN KEY(BNO) REFERENCES JUNGMIN_BOARD(BNO)
);

SELECT * FROM JUNGMIN_FILE ORDER BY BNO DESC;

ALTER TABLE JUNGMIN_FILE DROP CONSTRAINT FK_FILE;

ALTER TABLE JUNGMIN_FILE ADD CONSTRAINT FK_FILE FOREIGN KEY(BNO) REFERENCES JUNGMIN_BOARD(BNO) ON DELETE CASCADE;

TRUNCATE TABLE JUNGMIN_FILE;