
CREATE SEQUENCE SEQ_REPLY;

DROP TABLE JUNGMIN_REPLY;

CREATE TABLE JUNGMIN_REPLY(
	RNO NUMBER(10),
	BNO NUMBER(10),
	REPLY VARCHAR2(1000),
	REPLIER VARCHAR2(500),
	REPLYDATE DATE DEFAULT SYSDATE,
	UPDATEDATE DATE DEFAULT SYSDATE,
	CONSTRAINT PK_REPLY PRIMARY KEY(RNO),
	CONSTRAINT FK_REPLY_BOARD FOREIGN KEY(BNO) REFERENCES JUNGMIN_BOARD(BNO)
);

SELECT * FROM JUNGMIN_REPLY ORDER BY RNO DESC;

INSERT INTO JUNGMIN_REPLY(RNO, BNO, REPLY, REPLIER)
VALUES(SEQ_REPLY.NEXTVAL, 3094, '테스트4', '테스트4');